# Render deployment configuration for mg-dashboard
services:
  - type: web
    name: mg-dashboard
    runtime: node
    plan: free  # Change to starter or pro for production
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mg-dashboard-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard

databases:
  - name: mg-dashboard-db
    plan: free  # Change to starter or pro for production
    databaseName: mg_dashboard
    user: mg_dashboard_user

# Optional: Static site for frontend only (if you want to separate frontend/backend)
# - type: static
#   name: mg-dashboard-frontend
#   buildCommand: npm install && npm run build
#   staticPublishPath: ./out
#   envVars:
#     - key: NEXT_PUBLIC_API_URL
#       value: https://your-backend-url.onrender.com